
BASEURL = 'https://example.com:8443/api'

LIMIT = 30

EVENTS_TO_NOTIFY = [
    'EVT_WU_CONNECTED',
    'EVT_WU_DISCONNECTED',
    'EVT_WU_ROAM',
    'EVT_WU_ROAMRADIO',
    'EVT_WG_CONNECTED',
    'EVT_WG_DISCONNECTED',
    'EVT_Wg_ROAM',
    'EVT_WG_ROAMRADIO',
]

PASSWORD = ''
USERNAME = ''
