
baseurl: 'https://example.com:8443/api'

limit: 30

events_to_notify:
    - 'EVT_AP_DETECT_ROGUE_AP'
    - 'EVT_AP_RESTARTED'
    - 'EVT_AP_RESTARTED_UNKNOWN'
    - 'EVT_WU_CONNECTED'
    - 'EVT_WU_DISCONNECTED'
    - 'EVT_WU_ROAM'
    - 'EVT_WU_ROAMRADIO'
    - 'EVT_WG_CONNECTED'
    - 'EVT_WG_DISCONNECTED'
    - 'EVT_WG_ROAM'
    - 'EVT_WG_ROAMRADIO'


password: ''
username: ''

blacklist: []

pa_app_token: ''
pa_user_key: ''

